# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/iotsolar
spring.datasource.username=iotsolar
spring.datasource.password=iotsolar

# ===============================
# Logs pour Spring Security
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.example.security=DEBUG

mqtt.broker.address=192.168.1.105
mqtt.broker.port=1883
mqtt.broker.hasSSL=false
#mqtt.broker.userName=${mqtt-user}
#mqtt.broker.password=${mqtt-password}
