# ===============================
# DATABASE
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ===============================
# Logs pour Spring Security
# ===============================
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
logging.level.com.example.security=INFO

# ===============================
# MQTT / Mosquitto
# ===============================
mqtt.broker.address=${MQTT_BROKER_ADDRESS}
mqtt.broker.port=${MQTT_BROKER_PORT}
mqtt.broker.hasSSL=${MQTT_BROKER_HASSSL}
mqtt.broker.userName=${MQTT_BROKER_USERNAME}
mqtt.broker.password=${MQTT_BROKER_PASSWORD}