# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/iotsolar
spring.datasource.username=iotsolar
spring.datasource.password=iotsolar

# ===============================
# Logs pour Spring Security
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.example.security=DEBUG