spring.application.name=iot-solar-api
server.port=8080

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# ===============================
# JWT
# ===============================
security.jwt.secret-key=${secret-jwt-token}
# 1 jour en ms
security.jwt.expiration-time=86400000

# Désactive la sérialisation des dates en timestamps (utilise le format ISO-8601)
spring.jackson.serialization.write-dates-as-timestamps=false

# Désactive l'ajustement automatique des dates au fuseau horaire du contexte
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false
